### ISSUE TITLE
symlinks unsupported

### ISSUE THREAD

**Issue by mengesb** [Ericsson/puppet-module-nisclient#27]
There's a symlink in the module:

Warning: Symlinks in modules are unsupported. Please investigate symlink ericsson-nisclient-1.0.0/spec/fixtures/modules/nisclient->/Users/gh/git/puppet-module-nisclient.

This message occurs when downloading via the forge.

**Comment by ghoneycutt** [comment]
@jwennerberg Can you please remove v1.0.0 from the forge?

**Comment by ghoneycutt** [comment]
@mengesb suggest downloading from GitHub. It appears that the .gitignore was missing some lines

**Comment by ghoneycutt** [comment]
Created PR #28 to address this issue.

**Comment by Phil-Friderici** [comment]
Uploaded v1.1.0 and removed v1.0.0 from the forge.
