### ISSUE TITLE
optionally manage package on solaris

### ISSUE THREAD

**Issue by ghoneycutt** [Ericsson/puppet-module-nisclient#6]
The base system packages for Solaris are not generally available. @jwennerberg states that it is not standard practice to have them mounted via NFS and available for installs, which is why we want to optionally ensure the package.

Someone might have a different package name, in which case, we want the package resource to ensure it is installed and have `responsefile` and `source` attributes.

**Comment by Phil-Friderici** [comment]
Closing this issue as I haven't heard any complaints about this anymore.
